name: "Say hello on each push"
on:
  push: # executed on all push

jobs:
  say_hello: # first job declaration
    name: "Say hello"
    runs-on: ubuntu-latest
    steps:
      # The following step execute a shell script
      - name: "Install python"
        run: sudo apt update && sudo apt install python3 && sudo apt install python3-pip
      - name: "Install pylint"
        run: pip install pylint
      - name: "Test"
        run: pylint test.py